services:
  caddy:
    environment:
      - CHECKMATE_HOSTNAME=localhost
    ports:
      - '8080:80'
      - '8081:443'
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - build_prod:/srv:ro
      - log_prod:/log

  app:
    restart: unless-stopped
    environment:
      - BUILD_MODE=prod
      - CHECKMATE_HOSTNAME=localhost
      - CHECKMATE_BIND_PORT_HTTPS=8081
    volumes:
      - build_prod:/build/backend
      - log_prod:/log

volumes:
  build_prod:
  log_prod:
