services:
  caddy:
    environment:
      - 'CHECKMATE_HOSTNAME=${CHECKMATE_HOSTNAME?}'
    ports:
      - '${CHECKMATE_BIND_PORT_HTTP?}:80'
      - '${CHECKMATE_BIND_PORT_HTTPS?}:443'
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - build_prod:/srv:ro
      - log_prod:/log

  app:
    restart: unless-stopped
    environment:
      - BUILD_MODE=prod
      - 'CHECKMATE_HOSTNAME=${CHECKMATE_HOSTNAME?}'
      - 'CHECKMATE_BIND_PORT_HTTPS=${CHECKMATE_BIND_PORT_HTTPS?}'
    volumes:
      - build_prod:/build/backend
      - log_prod:/log

volumes:
  build_prod:
  log_prod:
