services:
  caddy:
    environment:
      - SERVER_HOSTNAME=localhost
    ports:
      - '8080:80'
      - '8081:443'
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - log_dev:/log

  app:
    environment:
      - BUILD_MODE=dev
      - SERVER_ORIGIN=https://localhost:8081
      - ASGI_NUM_PROCS=2
      - CELERY_NUM_PROCS=1
    volumes:
      - .:/app:rw
      - log_dev:/log

volumes:
  log_dev:
