services:
  caddy:
    restart: unless-stopped
    image: caddy:2.10.2-alpine
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  postgres:
    restart: unless-stopped
    image: postgres:18.1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/18/docker

  redis:
    restart: unless-stopped
    image: redis:8.4.0

  app:
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - ASGI_NUM_PROCS=4
      - CELERY_NUM_PROCS=2
    volumes:
      - .:/app:ro
      - ./frontend/.docker.yarnrc:/app/frontend/.yarnrc:ro
      - ./web-ext-artifacts:/web-ext-artifacts
      - /app/frontend/node_modules # ignore host node_modules
    depends_on:
      - postgres
      - redis

volumes:
  caddy_data:
  caddy_config:
  pgdata:
